# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokeDexIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeDexIOS
pod “Alamofire”

  target 'PokeDexIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokeDexIOSUITests' do
    # Pods for testing
  end

end
